### 11.2 Fichier `config.yml`
```yaml
# Chemins ------------------------------------------------------------------
ais_dir: "data/raw/ais"
sediment_file: "data/raw/seabed/seabed_lithology_with_pl.csv"
output_dir: "data/processed"

# Pré‑traitement AIS --------------------------------------------------------
core_years: [2012, 2024]

# Jointure sédiment ---------------------------------------------------------
max_dist_km: 10        # rayon pour le plus proche voisin

# Sous‑ensemble géographique ------------------------------------------------
mumbai_bbox: [72, 74, 18, 20]   # xmin, xmax, ymin, ymax

# Paramètres fi / SVR -------------------------------------------------------
penetration_depth_m: 1
alpha_deep: 0.25