name: Pipeline-CI

on:
  push:            { branches: [main] }
  pull_request:    { branches: [main] }
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    # → image avec R 4.4.3 + GDAL/GEOS/PROJ + pandoc
    container: rocker/geospatial:4.4.3

    env:
      RENV_PATHS_ROOT: ~/.local/share/renv

    steps:
    - uses: actions/checkout@v4

    # ------------------------------------------------------------------
    # 1. Restaurer l’environnement renv + cache binaire
    # ------------------------------------------------------------------
    - name: Restore renv cache & install packages
      uses: r-lib/actions/setup-renv@v2
      with:
        cache-version: 2          # ↺ forcer un nouveau cache si besoin

    # ------------------------------------------------------------------
    # 2. Exécuter la pipeline targets
    # ------------------------------------------------------------------
    - name: Run targets pipeline
      run: |
        Rscript -e 'targets::tar_make()'

    # ------------------------------------------------------------------
    # 3.  Infos de debug toujours affichées
    # ------------------------------------------------------------------
    - name: sessionInfo()
      if: always()
      run: Rscript -e 'sessionInfo()'

    # ------------------------------------------------------------------
    # 4.  Upload complet des logs si échec
    # ------------------------------------------------------------------
    - name: Upload runner logs
      if: failure()
      uses: actions/upload-artifact@v4
      with:
        name: full-runner-log
        path: ${{ runner.temp }}/_temp/_runner_files/*
