name: Pipeline-CI
on:
  push:
    branches: [main]
  pull_request:
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: r-lib/actions/setup-r@v2
      - uses: r-lib/actions/setup-renv@v2
      - name: Run pipeline
        run: Rscript -e "targets::tar_make(callr_function = NULL)"
      - name: Render report
        run: Rscript -e "rmarkdown::render('reports/pipeline_report.Rmd')"
      - uses: actions/upload-artifact@v4
        with:
          name: html-report
          path: reports/pipeline_report.html
