name: Pipeline-CI
on:
  push:
    branches: [main]

jobs:
  build:
    # GitHub a quand même besoin d'un runner hôte
    runs-on: ubuntu-latest

    # >>> Conteneur R + stack géospatiale complète <<<
    container:
      image: rocker/geospatial:4.4.3
      #   → R 4.4, GDAL, PROJ, GEOS, netCDF, etc.
      options: --user=1001  # évite des problèmes de permissions sur le cache

    steps:
      # 1) Checkout du code
      - uses: actions/checkout@v4
        with:
          fetch-depth: 1

      # 2) (Optionnel) apt-get remis “au cas où”
      - name: Ensure system libs (idempotent)
        run: |
          apt-get update -y
          apt-get install -y --no-install-recommends \
            gdal-bin libgdal-dev \
            libproj-dev proj-bin proj-data \
            libgeos-dev libnetcdf-dev || true

      # 3) Installation de R (déjà présent, mais setup-r règle les options)
      - uses: r-lib/actions/setup-r@v2
        with:
          r-version: '4.4'

      # 4) Renv : restaure (ou crée) le cache des paquets
      - uses: r-lib/actions/setup-renv@v2
        with:
          cache: true

      # 5) Exécution du pipeline
      - name: Run targets pipeline
        run: |
          Rscript -e "targets::tar_make()"
